//Eittipakorn Suntrakoon Sec3 116610905131-6

package teacherappointment;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class LandingPage extends javax.swing.JFrame {

    ImageIcon imageKhongthep = new ImageIcon("khongthep.png");
    ImageIcon imageUraiwan = new ImageIcon("uraiwan.png");
    ImageIcon imageWeena = new ImageIcon("weena.png");
    ImageIcon imageWaraphan = new ImageIcon("waraphan.png");
    
    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
        
        lblKhongthepPic.setText("");
        lblKhongthepPic.setIcon(imageKhongthep);
        
        lblUraiwanPic.setText("");
        lblUraiwanPic.setIcon(imageUraiwan);
        
        lblWaraphanPic.setText("");
        lblWaraphanPic.setIcon(imageWaraphan);
        
        lblWeenaPic.setText("");
        lblWeenaPic.setIcon(imageWeena);
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Are you sure to exit the program?",
                        "Exit",
                        JOptionPane.YES_NO_OPTION);
                
                if (confirmed == JOptionPane.YES_OPTION) {
                    dispose();
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblHeaderName = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        btnGetStarted = new javax.swing.JButton();
        lblMakeAppointmentIn3Steps = new javax.swing.JLabel();
        lblChooseEnterReviewFinish = new javax.swing.JLabel();
        lblAvailableTeacher = new javax.swing.JLabel();
        lblKhongthepPic = new javax.swing.JLabel();
        lblUraiwanPic = new javax.swing.JLabel();
        lblWaraphanPic = new javax.swing.JLabel();
        lblWeenaPic = new javax.swing.JLabel();
        lblKhongthep = new javax.swing.JLabel();
        lblBoonmee = new javax.swing.JLabel();
        lblWaraphan = new javax.swing.JLabel();
        lblSarasureeporn = new javax.swing.JLabel();
        lblUraiwan = new javax.swing.JLabel();
        lblInyaem = new javax.swing.JLabel();
        lblWeena = new javax.swing.JLabel();
        lblJanratchakool = new javax.swing.JLabel();
        lblMoreAvailableTeacherSoon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RMUTT Computer Science Teacher Appointment");

        pnlHeader.setBackground(new java.awt.Color(46, 64, 83));

        lblHeaderName.setBackground(new java.awt.Color(255, 255, 255));
        lblHeaderName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblHeaderName.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderName.setText("RMUTT Computer Science Teacher Appointment");

        lblSlogan.setBackground(new java.awt.Color(255, 255, 255));
        lblSlogan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setText("\"appoint, no disappoint\"");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeaderName)
                    .addComponent(lblSlogan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblHeaderName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSlogan)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnGetStarted.setText("Get started >");
        btnGetStarted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetStartedMouseClicked(evt);
            }
        });
        btnGetStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetStartedActionPerformed(evt);
            }
        });

        lblMakeAppointmentIn3Steps.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMakeAppointmentIn3Steps.setText("Make an appointment with teacher in 3 steps!");

        lblChooseEnterReviewFinish.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblChooseEnterReviewFinish.setText("Choose teacher > Enter details > Review > Finish!");

        lblAvailableTeacher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvailableTeacher.setText("Available teachers to make appointment with");

        lblKhongthepPic.setText("lblKhongthepPic");

        lblUraiwanPic.setText("lblUraiwanPic");

        lblWaraphanPic.setText("lblWaraphanPic");

        lblWeenaPic.setText("lblWeenaPic");

        lblKhongthep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKhongthep.setText("Khongthep");

        lblBoonmee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBoonmee.setText("Boonmee");

        lblWaraphan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWaraphan.setText("Waraphan");

        lblSarasureeporn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSarasureeporn.setText("Sarasureeporn");

        lblUraiwan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUraiwan.setText("Uraiwan");

        lblInyaem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInyaem.setText("Inyaem");

        lblWeena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWeena.setText("Weena");

        lblJanratchakool.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJanratchakool.setText("Janratchakool");

        lblMoreAvailableTeacherSoon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMoreAvailableTeacherSoon.setText("More available teachers soon ......");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoreAvailableTeacherSoon)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnGetStarted)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMakeAppointmentIn3Steps)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblChooseEnterReviewFinish))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblAvailableTeacher)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKhongthepPic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(lblUraiwanPic))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKhongthep)
                        .addGap(120, 120, 120)
                        .addComponent(lblUraiwan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBoonmee, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(lblInyaem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWaraphanPic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(lblWeenaPic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWaraphan)
                        .addGap(125, 125, 125)
                        .addComponent(lblWeena))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSarasureeporn)
                        .addGap(99, 99, 99)
                        .addComponent(lblJanratchakool)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblMakeAppointmentIn3Steps)
                .addGap(18, 18, 18)
                .addComponent(lblChooseEnterReviewFinish)
                .addGap(46, 46, 46)
                .addComponent(lblAvailableTeacher)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKhongthepPic)
                    .addComponent(lblUraiwanPic)
                    .addComponent(lblWaraphanPic)
                    .addComponent(lblWeenaPic))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKhongthep)
                    .addComponent(lblUraiwan)
                    .addComponent(lblWaraphan)
                    .addComponent(lblWeena))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoonmee)
                    .addComponent(lblInyaem)
                    .addComponent(lblSarasureeporn)
                    .addComponent(lblJanratchakool))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(lblMoreAvailableTeacherSoon)
                .addGap(30, 30, 30)
                .addComponent(btnGetStarted)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetStartedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetStartedActionPerformed

    private void btnGetStartedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetStartedMouseClicked
        MakeAppointment ma = new MakeAppointment();
        ma.show();
        dispose();
    }//GEN-LAST:event_btnGetStartedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetStarted;
    private javax.swing.JLabel lblAvailableTeacher;
    private javax.swing.JLabel lblBoonmee;
    private javax.swing.JLabel lblChooseEnterReviewFinish;
    private javax.swing.JLabel lblHeaderName;
    private javax.swing.JLabel lblInyaem;
    private javax.swing.JLabel lblJanratchakool;
    private javax.swing.JLabel lblKhongthep;
    private javax.swing.JLabel lblKhongthepPic;
    private javax.swing.JLabel lblMakeAppointmentIn3Steps;
    private javax.swing.JLabel lblMoreAvailableTeacherSoon;
    private javax.swing.JLabel lblSarasureeporn;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblUraiwan;
    private javax.swing.JLabel lblUraiwanPic;
    private javax.swing.JLabel lblWaraphan;
    private javax.swing.JLabel lblWaraphanPic;
    private javax.swing.JLabel lblWeena;
    private javax.swing.JLabel lblWeenaPic;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
