//Eittipakorn Suntrakoon Sec3 116610905131-6

package teacherappointment;

import java.awt.event.ItemEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Eittipakorn
 */
public class MakeAppointment extends javax.swing.JFrame {
    
    ImageIcon imageKhongthep = new ImageIcon("khongthep.png");
    ImageIcon imageUraiwan = new ImageIcon("uraiwan.png");
    ImageIcon imageWeena = new ImageIcon("weena.png");
    ImageIcon imageWaraphan = new ImageIcon("waraphan.png");

    /**
     * Creates new form MakeAppointment
     */
    public MakeAppointment() {
        initComponents();
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Are you sure to exit the program?",
                        "Exit",
                        JOptionPane.YES_NO_OPTION);
                
                if (confirmed == JOptionPane.YES_OPTION) {
                    dispose();
                }
            }
        });
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMakeAppointment1 = new javax.swing.JPanel();
        lblMAHeaderMakeAppointment = new javax.swing.JLabel();
        lblMATeacher = new javax.swing.JLabel();
        cmbMATeacher = new javax.swing.JComboBox<>();
        lblMATeacherPic = new javax.swing.JLabel();
        lblMAHeaderStep1A = new javax.swing.JLabel();
        lblMAName = new javax.swing.JLabel();
        lblMASurname = new javax.swing.JLabel();
        txtMAName = new javax.swing.JTextField();
        txtMASurname = new javax.swing.JTextField();
        lblMAFaculty = new javax.swing.JLabel();
        cmbMAFaculty = new javax.swing.JComboBox<>();
        lblMAPosition = new javax.swing.JLabel();
        lblMAToBeCalledName = new javax.swing.JLabel();
        txtMAToBeCalledName = new javax.swing.JTextField();
        cmbMAPosition = new javax.swing.JComboBox<>();
        lblMAPhoneNumber = new javax.swing.JLabel();
        txtMAPhoneNumber = new javax.swing.JTextField();
        lblMAEmail = new javax.swing.JLabel();
        txtMAEmail = new javax.swing.JTextField();
        lblMALINEID = new javax.swing.JLabel();
        txtMALINEID = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblMAHeaderStep1B = new javax.swing.JLabel();
        lblMAAppointmentTime = new javax.swing.JLabel();
        lblMADuration = new javax.swing.JLabel();
        lblMANoteContent1 = new javax.swing.JLabel();
        lblMAAppointmentDetail = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMAAppointmentDetail = new javax.swing.JTextArea();
        chkMAUrgent = new javax.swing.JCheckBox();
        lblMAMinutes = new javax.swing.JLabel();
        txtMADuration = new javax.swing.JTextField();
        txtMAMyTime = new javax.swing.JTextField();
        radMATeacherTime = new javax.swing.JRadioButton();
        radMAMyTime = new javax.swing.JRadioButton();
        lblMANoteHeader = new javax.swing.JLabel();
        lblMANoteContent2 = new javax.swing.JLabel();
        txtMAMajor = new javax.swing.JTextField();
        lblMAMajor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Make appointment");

        pnlMakeAppointment1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMAHeaderMakeAppointment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMAHeaderMakeAppointment.setText("Make appointment");

        lblMATeacher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMATeacher.setText("Teacher");

        cmbMATeacher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMATeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select teacher -", "Khongthep Boonmee", "Uraiwan Inyaem", "Waraphan Sarasureeporn", "Weena Janratchakool" }));
        cmbMATeacher.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMATeacherItemStateChanged(evt);
            }
        });

        lblMATeacherPic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMAHeaderStep1A.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMAHeaderStep1A.setText("Enter appointer details");

        lblMAName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAName.setText("Name");

        lblMASurname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMASurname.setText("Surname");

        txtMAName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMAName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMANameActionPerformed(evt);
            }
        });

        txtMASurname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMASurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMASurnameActionPerformed(evt);
            }
        });

        lblMAFaculty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAFaculty.setText("Faculty");

        cmbMAFaculty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMAFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select faculty -", "Faculty of Liberal Arts", "Faculty of Technical Education", "Faculty of Agricultural Technology", "Faculty of Engineering", "Faculty of Business Administration", "Faculty of Home Economics Technology", "Faculty of Fine and Applied Arts", "Faculty of Mass Communication Technology", "Faculty of Science and Technology", "Faculty of Architecture", "Faculty of Integrative Medicine", "Faculty of Nursing", "Other" }));
        cmbMAFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMAFacultyActionPerformed(evt);
            }
        });

        lblMAPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAPosition.setText("Position");

        lblMAToBeCalledName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAToBeCalledName.setText("To be called name");

        txtMAToBeCalledName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMAToBeCalledName.setText("(Optonal)");
        txtMAToBeCalledName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMAToBeCalledNameActionPerformed(evt);
            }
        });

        cmbMAPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMAPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select position -", "Student", "Teacher", "Personel", "Other" }));

        lblMAPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAPhoneNumber.setText("Phone number");

        txtMAPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMAEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAEmail.setText("Email");

        txtMAEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMAEmail.setText("(Optional)");

        lblMALINEID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMALINEID.setText("LINE ID");

        txtMALINEID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMALINEID.setText("(Optonal)");
        txtMALINEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMALINEIDActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNext.setText("Next");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblMAHeaderStep1B.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMAHeaderStep1B.setText("Enter appointment details");

        lblMAAppointmentTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAAppointmentTime.setText("Appointment Time");

        lblMADuration.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMADuration.setText("Duration");

        lblMANoteContent1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMANoteContent1.setText("Appointment can only be made in the week during which an appointment has");

        lblMAAppointmentDetail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAAppointmentDetail.setText("Appointment detail");

        txtMAAppointmentDetail.setColumns(20);
        txtMAAppointmentDetail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMAAppointmentDetail.setLineWrap(true);
        txtMAAppointmentDetail.setRows(5);
        txtMAAppointmentDetail.setAutoscrolls(false);
        jScrollPane2.setViewportView(txtMAAppointmentDetail);

        chkMAUrgent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkMAUrgent.setText("Urgent");
        chkMAUrgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMAUrgentActionPerformed(evt);
            }
        });

        lblMAMinutes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAMinutes.setText("Minutes");

        txtMADuration.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMAMyTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMAMyTime.setText("(Example : Wed 13:30)");
        txtMAMyTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMAMyTimeActionPerformed(evt);
            }
        });

        buttonGroup1.add(radMATeacherTime);
        radMATeacherTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radMATeacherTime.setText("Teacher's available time");
        radMATeacherTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMATeacherTimeActionPerformed(evt);
            }
        });

        buttonGroup1.add(radMAMyTime);
        radMAMyTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radMAMyTime.setText("My available time");
        radMAMyTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMAMyTimeActionPerformed(evt);
            }
        });

        cmbMATeacherTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMATeacherTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select teacher first -" }));

        lblMANoteHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMANoteHeader.setText("*Note");

        lblMANoteContent2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMANoteContent2.setText("been made.");

        txtMAMajor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMAMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMAMajorActionPerformed(evt);
            }
        });

        lblMAMajor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMAMajor.setText("Major");

        javax.swing.GroupLayout pnlMakeAppointment1Layout = new javax.swing.GroupLayout(pnlMakeAppointment1);
        pnlMakeAppointment1.setLayout(pnlMakeAppointment1Layout);
        pnlMakeAppointment1Layout.setHorizontalGroup(
            pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMALINEID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMAEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMAPhoneNumber)
                    .addComponent(lblMAPosition)
                    .addComponent(lblMAMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                            .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                                    .addComponent(lblMAName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMAName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblMATeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                                    .addComponent(lblMASurname)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMASurname))
                                .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(cmbMATeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                            .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                                    .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMAToBeCalledName)
                                        .addComponent(lblMAFaculty))
                                    .addGap(169, 169, 169)
                                    .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbMAFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmbMAPosition, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                            .addComponent(txtMAPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMALINEID, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMAEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMAMajor, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(txtMAToBeCalledName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblMAHeaderMakeAppointment)
                                .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMATeacherPic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMAHeaderStep1A)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE))))
                .addGap(50, 50, 50)
                .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMakeAppointment1Layout.createSequentialGroup()
                            .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radMATeacherTime, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                                    .addGap(263, 263, 263)
                                    .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbMATeacherTime, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMAMyTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(125, 125, 125))
                        .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                            .addGap(284, 284, 284)
                            .addComponent(txtMADuration, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblMAMinutes)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMANoteHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMANoteContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                                                .addComponent(btnNext)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnClear)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCancel))
                                            .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblMAAppointmentTime)
                                                .addComponent(chkMAUrgent)
                                                .addComponent(lblMAAppointmentDetail)
                                                .addComponent(lblMADuration)
                                                .addComponent(lblMAHeaderStep1B)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(radMAMyTime, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(37, 37, 37)))
                                .addComponent(lblMANoteContent2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap())))
        );
        pnlMakeAppointment1Layout.setVerticalGroup(
            pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                        .addComponent(lblMAHeaderStep1B)
                        .addGap(32, 32, 32)
                        .addComponent(lblMAAppointmentTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radMATeacherTime)
                            .addComponent(cmbMATeacherTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMAMyTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radMAMyTime))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMADuration)
                            .addComponent(txtMADuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMAMinutes))
                        .addGap(30, 30, 30)
                        .addComponent(lblMANoteHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMANoteContent1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMANoteContent2)
                        .addGap(30, 30, 30)
                        .addComponent(lblMAAppointmentDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkMAUrgent)
                        .addGap(36, 36, 36)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnClear)
                            .addComponent(btnNext)))
                    .addGroup(pnlMakeAppointment1Layout.createSequentialGroup()
                        .addComponent(lblMAHeaderMakeAppointment)
                        .addGap(38, 38, 38)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMATeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMATeacher)
                            .addComponent(lblMATeacherPic))
                        .addGap(47, 47, 47)
                        .addComponent(lblMAHeaderStep1A)
                        .addGap(27, 27, 27)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMAName)
                            .addComponent(lblMASurname)
                            .addComponent(txtMASurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMAToBeCalledName)
                            .addComponent(txtMAToBeCalledName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMAFaculty)
                            .addComponent(cmbMAFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMAMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMAMajor))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMAPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMAPosition))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMAPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMAPhoneNumber))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMAEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMAEmail))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMakeAppointment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMALINEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMALINEID))))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMakeAppointment1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlMakeAppointment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMAMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAMajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMAMajorActionPerformed

    private void radMAMyTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMAMyTimeActionPerformed
        if(radMAMyTime.isSelected()) {
            cmbMATeacherTime.setEnabled(false);
            txtMAMyTime.setEnabled(true);
        }
    }//GEN-LAST:event_radMAMyTimeActionPerformed

    private void radMATeacherTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMATeacherTimeActionPerformed
        if(radMATeacherTime.isSelected()) {
            cmbMATeacherTime.setEnabled(true);
            txtMAMyTime.setEnabled(false);
        }
    }//GEN-LAST:event_radMATeacherTimeActionPerformed

    private void txtMAMyTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAMyTimeActionPerformed
        
    }//GEN-LAST:event_txtMAMyTimeActionPerformed

    private void chkMAUrgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMAUrgentActionPerformed

    }//GEN-LAST:event_chkMAUrgentActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        ReviewAppointment ra = new ReviewAppointment();
        
        //Appointer
        ra.cmbRATeacher.setSelectedItem((String)cmbMATeacher.getSelectedItem());
        ra.txtRAName.setText(txtMAName.getText());
        ra.txtRASurname.setText(txtMASurname.getText());
        ra.txtRAToBeCalledName.setText(txtMAToBeCalledName.getText());
        ra.cmbRAFaculty.setSelectedItem((String)cmbMAFaculty.getSelectedItem());
        ra.txtRAMajor.setText(txtMAMajor.getText());
        ra.cmbRAPosition.setSelectedItem((String)cmbMAPosition.getSelectedItem());
        ra.txtRAPhoneNumber.setText(txtMAPhoneNumber.getText());
        ra.txtRAEmail.setText(txtMAEmail.getText());
        ra.txtRALINEID.setText(txtMALINEID.getText());
        
        //Appointment
        if(radMATeacherTime.isSelected()) {
            DefaultComboBoxModel modelRA = new DefaultComboBoxModel();
            modelRA.addElement(cmbMATeacherTime.getSelectedItem());
            ra.cmbRATeacherTime.setModel(modelRA);
            ra.txtRAMyTime.setText(null);
            ra.txtRAMyTime.setEnabled(false);
            ra.radRATeacherTime.setSelected(true);
        }
        else {
            ra.txtRAMyTime.setText(txtMAMyTime.getText());
            DefaultComboBoxModel modelRA = new DefaultComboBoxModel();
            modelRA.addElement(null);
            ra.cmbRATeacherTime.setModel(modelRA);
            ra.cmbRATeacherTime.setEnabled(false);
        }
        
        ra.txtRADuration.setText(txtMADuration.getText());
        ra.txtRAAppointmentDetail.setText(txtMAAppointmentDetail.getText());
        
        if(chkMAUrgent.isSelected()) {
            ra.chkRAUrgent.setSelected(true);
        }
        else {
            ra.chkRAUrgent.setSelected(false);
        }
        
        if(cmbMATeacher.getSelectedItem().toString().equals("Khongthep Boonmee")) {
            ra.lblRATeacherPic.setIcon(imageKhongthep);
        }
        
        if(cmbMATeacher.getSelectedItem().toString().equals("Uraiwan Inyaem")) {
            ra.lblRATeacherPic.setIcon(imageUraiwan);
        }
        
        if(cmbMATeacher.getSelectedItem().toString().equals("Waraphan Sarasureeporn")) {
            ra.lblRATeacherPic.setIcon(imageWaraphan);
        }
        
        if(cmbMATeacher.getSelectedItem().toString().equals("Weena Janratchakool")) {
            ra.lblRATeacherPic.setIcon(imageWeena);
        }
        
        ra.show();
        dispose();
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        LandingPage ldp = new LandingPage();
        ldp.show();
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtMALINEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMALINEIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMALINEIDActionPerformed

    private void txtMAToBeCalledNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAToBeCalledNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMAToBeCalledNameActionPerformed

    private void cmbMAFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMAFacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMAFacultyActionPerformed

    private void txtMASurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMASurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMASurnameActionPerformed

    private void txtMANameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMANameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMANameActionPerformed

    private void cmbMATeacherItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMATeacherItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED) {
            if(cmbMATeacher.getSelectedItem().toString().equals("Khongthep Boonmee")) {
                lblMATeacherPic.setIcon(imageKhongthep);
                DefaultComboBoxModel model = new DefaultComboBoxModel();
                model.addElement("- Select available time -");
                model.addElement("Mon 12:00");
                model.addElement("Mon 16:00");
                model.addElement("Tue 12:00");
                model.addElement("Wed 09:30");
                model.addElement("Wed 16:00");
                model.addElement("Fri 09:30");
                cmbMATeacherTime.setModel(model);
            }
            
            if(cmbMATeacher.getSelectedItem().toString().equals("Uraiwan Inyaem")) {
                lblMATeacherPic.setIcon(imageUraiwan);
                DefaultComboBoxModel model = new DefaultComboBoxModel();
                model.addElement("- Select available time -");
                model.addElement("Mon 12:00");
                model.addElement("Mon 16:00");
                model.addElement("Tue 12:00");
                model.addElement("Tue 16:00");
                model.addElement("Wed 12:00");
                model.addElement("Wed 16:00");
                model.addElement("Thu 12:00");
                model.addElement("Thu 16:00");
                model.addElement("Fri 12:00");
                model.addElement("Fri 16:00");
                cmbMATeacherTime.setModel(model);
            }
            
            if(cmbMATeacher.getSelectedItem().toString().equals("Waraphan Sarasureeporn")) {
                lblMATeacherPic.setIcon(imageWaraphan);
                DefaultComboBoxModel model = new DefaultComboBoxModel();
                model.addElement("- Select available time -");
                model.addElement("Tue 16:00");
                model.addElement("Wed 10:00");
                model.addElement("Wed 16:00");
                model.addElement("Thu 09:00");
                cmbMATeacherTime.setModel(model);
            }
            
            if(cmbMATeacher.getSelectedItem().toString().equals("Weena Janratchakool")) {
                lblMATeacherPic.setIcon(imageWeena);
                DefaultComboBoxModel model = new DefaultComboBoxModel();
                model.addElement("- Select available time -");
                model.addElement("Fri 12:00");
                cmbMATeacherTime.setModel(model);
            }
            
            if(cmbMATeacher.getSelectedItem().toString().equals("- Select teacher -")) {
                lblMATeacherPic.setIcon(null);
                DefaultComboBoxModel model = new DefaultComboBoxModel();
                model.addElement("- Select teacher first -");
                cmbMATeacherTime.setModel(model);
            }
        }
    }//GEN-LAST:event_cmbMATeacherItemStateChanged

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        //clear appointer detail
        txtMAName.setText(null);
        txtMASurname.setText(null);
        txtMAToBeCalledName.setText("(Optional)");
        cmbMAFaculty.setSelectedItem("- Select faculty -");
        txtMAMajor.setText(null);
        cmbMAPosition.setSelectedItem("- Select position -");
        txtMAPhoneNumber.setText(null);
        txtMAEmail.setText("(Optional)");
        txtMALINEID.setText("(Optional)");
        
        //clear appointment detail
        cmbMATeacher.setSelectedItem("- Select teacher -");
        
        if(radMATeacherTime.isSelected() || radMAMyTime.isSelected()) {
            buttonGroup1.clearSelection();
        }
        
        cmbMATeacherTime.setSelectedItem("- Select teacher first -");
        txtMAMyTime.setText("(Example : Wed 13:30)");
        txtMADuration.setText(null);
        txtMAAppointmentDetail.setText(null);
        chkMAUrgent.setSelected(false);
        
    }//GEN-LAST:event_btnClearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkMAUrgent;
    private javax.swing.JComboBox<String> cmbMAFaculty;
    private javax.swing.JComboBox<String> cmbMAPosition;
    private javax.swing.JComboBox<String> cmbMATeacher;
    public final javax.swing.JComboBox<String> cmbMATeacherTime = new javax.swing.JComboBox<>();
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMAAppointmentDetail;
    private javax.swing.JLabel lblMAAppointmentTime;
    private javax.swing.JLabel lblMADuration;
    private javax.swing.JLabel lblMAEmail;
    private javax.swing.JLabel lblMAFaculty;
    private javax.swing.JLabel lblMAHeaderMakeAppointment;
    private javax.swing.JLabel lblMAHeaderStep1A;
    private javax.swing.JLabel lblMAHeaderStep1B;
    private javax.swing.JLabel lblMALINEID;
    private javax.swing.JLabel lblMAMajor;
    private javax.swing.JLabel lblMAMinutes;
    private javax.swing.JLabel lblMAName;
    private javax.swing.JLabel lblMANoteContent1;
    private javax.swing.JLabel lblMANoteContent2;
    private javax.swing.JLabel lblMANoteHeader;
    private javax.swing.JLabel lblMAPhoneNumber;
    private javax.swing.JLabel lblMAPosition;
    private javax.swing.JLabel lblMASurname;
    private javax.swing.JLabel lblMATeacher;
    private javax.swing.JLabel lblMATeacherPic;
    private javax.swing.JLabel lblMAToBeCalledName;
    private javax.swing.JPanel pnlMakeAppointment1;
    private javax.swing.JRadioButton radMAMyTime;
    private javax.swing.JRadioButton radMATeacherTime;
    private javax.swing.JTextArea txtMAAppointmentDetail;
    public javax.swing.JTextField txtMADuration;
    private javax.swing.JTextField txtMAEmail;
    private javax.swing.JTextField txtMALINEID;
    public javax.swing.JTextField txtMAMajor;
    public javax.swing.JTextField txtMAMyTime;
    private javax.swing.JTextField txtMAName;
    private javax.swing.JTextField txtMAPhoneNumber;
    private javax.swing.JTextField txtMASurname;
    private javax.swing.JTextField txtMAToBeCalledName;
    // End of variables declaration//GEN-END:variables
}
