//Eittipakorn Suntrakoon Sec3 116610905131-6

package teacherappointment;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

/**
 *
 * @author Eittipakorn
 */
public class ReviewAppointment extends javax.swing.JFrame {

    ImageIcon imageKhongthep = new ImageIcon("khongthep.png");
    ImageIcon imageUraiwan = new ImageIcon("uraiwan.png");
    ImageIcon imageWeena = new ImageIcon("weena.png");
    ImageIcon imageWaraphan = new ImageIcon("waraphan.png");
    

    
    
    /**
     * Creates new form MakeAppointment
     */
    public ReviewAppointment() {
        initComponents();
        
        //set appointer details uneditable
        txtRAName.setEditable(false);
        txtRASurname.setEditable(false);
        txtRAToBeCalledName.setEditable(false);
        cmbRAFaculty.setEnabled(false);
        txtRAMajor.setEditable(false);
        cmbRAPosition.setEnabled(false);
        txtRAPhoneNumber.setEditable(false);
        txtRAEmail.setEditable(false);
        txtRALINEID.setEditable(false);
        
        //set appointer details uneditable
        cmbRATeacher.setEnabled(false);
        radRATeacherTime.setEnabled(false);
        cmbRATeacherTime.setEnabled(false);
        radRAMyTime.setEnabled(false);
        txtRAMyTime.setEditable(false);
        txtRADuration.setEditable(false);
        txtRAAppointmentDetail.setEditable(false);
        chkRAUrgent.setEnabled(false);
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Are you sure to exit the program?",
                        "Exit",
                        JOptionPane.YES_NO_OPTION);
                
                if (confirmed == JOptionPane.YES_OPTION) {
                    dispose();
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReviewAppointment = new javax.swing.JPanel();
        lblRAHeaderReviewAppointment = new javax.swing.JLabel();
        lblRATeacher = new javax.swing.JLabel();
        cmbRATeacher = new javax.swing.JComboBox<>();
        lblRATeacherPic = new javax.swing.JLabel();
        lblRAHeaderStep1A = new javax.swing.JLabel();
        lblRAName = new javax.swing.JLabel();
        lblRASurname = new javax.swing.JLabel();
        txtRAName = new javax.swing.JTextField();
        txtRASurname = new javax.swing.JTextField();
        lblRAFaculty = new javax.swing.JLabel();
        cmbRAFaculty = new javax.swing.JComboBox<>();
        lblRAPosition = new javax.swing.JLabel();
        lblRAToBeCalledName = new javax.swing.JLabel();
        txtRAToBeCalledName = new javax.swing.JTextField();
        cmbRAPosition = new javax.swing.JComboBox<>();
        lblRAPhoneNumber = new javax.swing.JLabel();
        txtRAPhoneNumber = new javax.swing.JTextField();
        lblRAEmail = new javax.swing.JLabel();
        txtRAEmail = new javax.swing.JTextField();
        lblRALINEID = new javax.swing.JLabel();
        txtRALINEID = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblRAHeaderStep2B = new javax.swing.JLabel();
        lblRAAppointmentTime = new javax.swing.JLabel();
        lblRADuration = new javax.swing.JLabel();
        lblRANoteContent1 = new javax.swing.JLabel();
        lblRAAppointmentDetail = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRAAppointmentDetail = new javax.swing.JTextArea();
        chkRAUrgent = new javax.swing.JCheckBox();
        lblRAMinutes = new javax.swing.JLabel();
        txtRADuration = new javax.swing.JTextField();
        txtRAMyTime = new javax.swing.JTextField();
        radRATeacherTime = new javax.swing.JRadioButton();
        radRAMyTime = new javax.swing.JRadioButton();
        cmbRATeacherTime = new javax.swing.JComboBox<>();
        lblRANoteHeader = new javax.swing.JLabel();
        lblRANoteContent2 = new javax.swing.JLabel();
        txtRAMajor = new javax.swing.JTextField();
        lblRAMajor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Review appointment");

        pnlReviewAppointment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblRAHeaderReviewAppointment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRAHeaderReviewAppointment.setText("Review appointment");

        lblRATeacher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRATeacher.setText("Teacher");

        cmbRATeacher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRATeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select teacher -", "Khongthep Boonmee", "Uraiwan Inyaem", "Waraphan Sarasureeporn", "Weena Janratchakool" }));

        lblRATeacherPic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblRAHeaderStep1A.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRAHeaderStep1A.setText("Review appointer details");

        lblRAName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAName.setText("Name");

        lblRASurname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRASurname.setText("Surname");

        txtRAName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRAName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRANameActionPerformed(evt);
            }
        });

        txtRASurname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRASurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRASurnameActionPerformed(evt);
            }
        });

        lblRAFaculty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAFaculty.setText("Faculty");

        cmbRAFaculty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRAFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Faculty -", "Faculty of Liberal Arts", "Faculty of Technical Education", "Faculty of Agricultural Technology", "Faculty of Engineering", "Faculty of Business Administration", "Faculty of Home Economics Technology", "Faculty of Fine and Applied Arts", "Faculty of Mass Communication Technology", "Faculty of Science and Technology", "Faculty of Architecture", "Faculty of Integrative Medicine", "Faculty of Nursing", "Other" }));
        cmbRAFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRAFacultyActionPerformed(evt);
            }
        });

        lblRAPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAPosition.setText("Position");

        lblRAToBeCalledName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAToBeCalledName.setText("To be called name");

        txtRAToBeCalledName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRAToBeCalledName.setText("(Optonal)");
        txtRAToBeCalledName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRAToBeCalledNameActionPerformed(evt);
            }
        });

        cmbRAPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRAPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Position -", "Student", "Teacher", "Personel", "Other" }));

        lblRAPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAPhoneNumber.setText("Phone number");

        txtRAPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblRAEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAEmail.setText("Email");

        txtRAEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRAEmail.setText("(Optional)");

        lblRALINEID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRALINEID.setText("LINE ID");

        txtRALINEID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRALINEID.setText("(Optonal)");
        txtRALINEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRALINEIDActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblRAHeaderStep2B.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRAHeaderStep2B.setText("Review appointment details");

        lblRAAppointmentTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAAppointmentTime.setText("Appointment Time");

        lblRADuration.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRADuration.setText("Duration");

        lblRANoteContent1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRANoteContent1.setText("Appointment can only be made in the week during which an appointment has");

        lblRAAppointmentDetail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAAppointmentDetail.setText("Appointment detail");

        txtRAAppointmentDetail.setColumns(20);
        txtRAAppointmentDetail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRAAppointmentDetail.setLineWrap(true);
        txtRAAppointmentDetail.setRows(5);
        txtRAAppointmentDetail.setAutoscrolls(false);
        jScrollPane2.setViewportView(txtRAAppointmentDetail);

        chkRAUrgent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkRAUrgent.setText("Urgent");
        chkRAUrgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRAUrgentActionPerformed(evt);
            }
        });

        lblRAMinutes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAMinutes.setText("Minutes");

        txtRADuration.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtRAMyTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRAMyTime.setText("(eg. Wed 13:30)");
        txtRAMyTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRAMyTimeActionPerformed(evt);
            }
        });

        radRATeacherTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radRATeacherTime.setText("Teacher's available time");
        radRATeacherTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radRATeacherTimeActionPerformed(evt);
            }
        });

        radRAMyTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radRAMyTime.setText("My available time");
        radRAMyTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radRAMyTimeActionPerformed(evt);
            }
        });

        cmbRATeacherTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblRANoteHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblRANoteHeader.setText("*Note");

        lblRANoteContent2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRANoteContent2.setText("been made.");

        txtRAMajor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRAMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRAMajorActionPerformed(evt);
            }
        });

        lblRAMajor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRAMajor.setText("Major");

        javax.swing.GroupLayout pnlReviewAppointmentLayout = new javax.swing.GroupLayout(pnlReviewAppointment);
        pnlReviewAppointment.setLayout(pnlReviewAppointmentLayout);
        pnlReviewAppointmentLayout.setHorizontalGroup(
            pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRALINEID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRAEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRAPhoneNumber)
                    .addComponent(lblRAPosition)
                    .addComponent(lblRAMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                            .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                                    .addComponent(lblRAName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtRAName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblRATeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                                    .addComponent(lblRASurname)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtRASurname))
                                .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(cmbRATeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                            .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                                    .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblRAToBeCalledName)
                                        .addComponent(lblRAFaculty))
                                    .addGap(169, 169, 169)
                                    .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbRAFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmbRAPosition, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                            .addComponent(txtRAPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRALINEID, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRAEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRAMajor, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(txtRAToBeCalledName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblRAHeaderReviewAppointment)
                                .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRATeacherPic)
                                    .addComponent(lblRAHeaderStep1A)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE))))
                .addGap(50, 50, 50)
                .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReviewAppointmentLayout.createSequentialGroup()
                            .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radRATeacherTime, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                                    .addGap(263, 263, 263)
                                    .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbRATeacherTime, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtRAMyTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(131, 131, 131))
                        .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                            .addGap(284, 284, 284)
                            .addComponent(txtRADuration, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblRAMinutes)))
                    .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRANoteHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblRANoteContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                                                .addComponent(btnSubmit)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEdit)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCancel))
                                            .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblRAAppointmentTime)
                                                .addComponent(chkRAUrgent)
                                                .addComponent(lblRAAppointmentDetail)
                                                .addComponent(lblRADuration)
                                                .addComponent(lblRAHeaderStep2B)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(radRAMyTime, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(37, 37, 37)))
                                .addComponent(lblRANoteContent2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap())))
        );
        pnlReviewAppointmentLayout.setVerticalGroup(
            pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                        .addComponent(lblRAHeaderStep2B)
                        .addGap(32, 32, 32)
                        .addComponent(lblRAAppointmentTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radRATeacherTime)
                            .addComponent(cmbRATeacherTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRAMyTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radRAMyTime))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRADuration)
                            .addComponent(txtRADuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRAMinutes))
                        .addGap(30, 30, 30)
                        .addComponent(lblRANoteHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRANoteContent1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRANoteContent2)
                        .addGap(30, 30, 30)
                        .addComponent(lblRAAppointmentDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkRAUrgent)
                        .addGap(36, 36, 36)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnEdit)
                            .addComponent(btnSubmit)))
                    .addGroup(pnlReviewAppointmentLayout.createSequentialGroup()
                        .addComponent(lblRAHeaderReviewAppointment)
                        .addGap(38, 38, 38)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRATeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRATeacher)
                            .addComponent(lblRATeacherPic))
                        .addGap(47, 47, 47)
                        .addComponent(lblRAHeaderStep1A)
                        .addGap(27, 27, 27)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRAName)
                            .addComponent(lblRASurname)
                            .addComponent(txtRASurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRAToBeCalledName)
                            .addComponent(txtRAToBeCalledName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRAFaculty)
                            .addComponent(cmbRAFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRAMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRAMajor))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRAPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRAPosition))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRAPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRAPhoneNumber))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRAEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRAEmail))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReviewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRALINEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRALINEID))))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReviewAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlReviewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRAMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRAMajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRAMajorActionPerformed

    private void radRAMyTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radRAMyTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radRAMyTimeActionPerformed

    private void radRATeacherTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radRATeacherTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radRATeacherTimeActionPerformed

    private void txtRAMyTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRAMyTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRAMyTimeActionPerformed

    private void chkRAUrgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRAUrgentActionPerformed

    }//GEN-LAST:event_chkRAUrgentActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        String msg = "Appointment complete!"
                + "\n\nWait for the teacher to contact you back soon."
                + "\nYou may check the appointment transaction slip in the file of this program."
                + "\n\nThank you!";
        JOptionPane.showMessageDialog(this, msg);
        
        BufferedWriter out = null;
        
        try {
            out = new BufferedWriter(new FileWriter("appointment_transaction_slip.txt"));
            out.write("---------- Appointment Transaction Slip ----------");
            out.newLine();
            out.newLine();
            out.newLine();
            out.write("- Appointer details -");
            out.newLine();
            out.write("> Name  :  " + txtRAName.getText() + "    Surname  :  " + txtRASurname.getText());
            out.newLine();
            out.write("> To be called name  :  " + txtRAToBeCalledName.getText());
            out.newLine();
            out.write("> Faculty  :  " + cmbRAFaculty.getSelectedItem());
            out.newLine();
            out.write("> Major  :  " + txtRAMajor.getText());
            out.newLine();
            out.write("> Position  :  " + cmbRAPosition.getSelectedItem());
            out.newLine();
            out.write("> Email  :  " + txtRAEmail.getText());
            out.newLine();
            out.write("> LINE ID  :  " + txtRALINEID.getText());
            out.newLine();
            out.newLine();
            out.write("- Appointment details -");
            out.newLine();
            out.write("> Teacher  :  " + cmbRATeacher.getSelectedItem());
            out.newLine();
            out.write("> Appointment Time  :  ");
            if(radRATeacherTime.isSelected()) {
                out.newLine();
                out.write("    " + radRATeacherTime.getText() + "  " + cmbRATeacherTime.getSelectedItem());
                out.newLine();
            }
            else {
                out.newLine();
                out.write("    " + radRAMyTime.getText() + "  " + txtRAMyTime.getText());
                out.newLine();
            }
            out.write("> Duration  :  " + txtRADuration.getText() + " Minutes");
            out.newLine();
            out.newLine();
            out.write("> Appointment detail");
            out.newLine();
            out.write("    " + txtRAAppointmentDetail.getText());
            out.newLine();
            out.newLine();
            if(chkRAUrgent.isSelected()) {
                out.write("> Urgent  :  Yes");
            }
            else {
                out.write("> Urgent  :  No");
            }
            out.close();
        }
        
        catch(IOException e) {
            e.printStackTrace();
        }
        
        System.exit(0);
        
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        LandingPage ldp = new LandingPage();
        ldp.show();
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtRALINEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRALINEIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRALINEIDActionPerformed

    private void txtRAToBeCalledNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRAToBeCalledNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRAToBeCalledNameActionPerformed

    private void cmbRAFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRAFacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRAFacultyActionPerformed

    private void txtRASurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRASurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRASurnameActionPerformed

    private void txtRANameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRANameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRANameActionPerformed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        MakeAppointment ma = new MakeAppointment();    
                
        ma.show();
        dispose();
    }//GEN-LAST:event_btnEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSubmit;
    public javax.swing.JCheckBox chkRAUrgent;
    public javax.swing.JComboBox<String> cmbRAFaculty;
    public javax.swing.JComboBox<String> cmbRAPosition;
    public javax.swing.JComboBox<String> cmbRATeacher;
    public javax.swing.JComboBox<String> cmbRATeacherTime;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRAAppointmentDetail;
    private javax.swing.JLabel lblRAAppointmentTime;
    private javax.swing.JLabel lblRADuration;
    private javax.swing.JLabel lblRAEmail;
    private javax.swing.JLabel lblRAFaculty;
    private javax.swing.JLabel lblRAHeaderReviewAppointment;
    private javax.swing.JLabel lblRAHeaderStep1A;
    private javax.swing.JLabel lblRAHeaderStep2B;
    private javax.swing.JLabel lblRALINEID;
    private javax.swing.JLabel lblRAMajor;
    private javax.swing.JLabel lblRAMinutes;
    private javax.swing.JLabel lblRAName;
    private javax.swing.JLabel lblRANoteContent1;
    private javax.swing.JLabel lblRANoteContent2;
    private javax.swing.JLabel lblRANoteHeader;
    private javax.swing.JLabel lblRAPhoneNumber;
    private javax.swing.JLabel lblRAPosition;
    private javax.swing.JLabel lblRASurname;
    private javax.swing.JLabel lblRATeacher;
    public javax.swing.JLabel lblRATeacherPic;
    private javax.swing.JLabel lblRAToBeCalledName;
    public javax.swing.JPanel pnlReviewAppointment;
    public javax.swing.JRadioButton radRAMyTime;
    public javax.swing.JRadioButton radRATeacherTime;
    public javax.swing.JTextArea txtRAAppointmentDetail;
    public javax.swing.JTextField txtRADuration;
    public javax.swing.JTextField txtRAEmail;
    public javax.swing.JTextField txtRALINEID;
    public javax.swing.JTextField txtRAMajor;
    public javax.swing.JTextField txtRAMyTime;
    public javax.swing.JTextField txtRAName;
    public javax.swing.JTextField txtRAPhoneNumber;
    public javax.swing.JTextField txtRASurname;
    public javax.swing.JTextField txtRAToBeCalledName;
    // End of variables declaration//GEN-END:variables
}
